channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - albumentations=1.2.1
  - cudatoolkit=11.6
  - imgaug=0.4.0
  - jupyter=1.0.0
  - jupyterlab=3.4.5
  - matplotlib=3.7.3
  - mkl=2022.*
  - nodejs=16.12.0
  - numpy=1.22.4
  - opencv=4.4.0
  - pandas=1.4.3
  - pip=22.2.2
  - python=3.8.13
  - pytorch=1.12.1
  - pytorch-lightning=1.9.5
  - pyyaml=6.0
  - scikit-image=0.19.3
  - scikit-learn=1.3.2
  - scipy=1.8.1
  - sympy=1.10.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pip:
    - opencv-contrib-python==4.4.0.46
    - opencv-python-headless==4.4.0.46
    - pynrrd==1.0.0
    - seaborn==0.13.0
    - timm==0.6.12
    - torcheval==0.0.7
    - monai==1.1.0
    - lmdb==1.4.1
    - rich==13.4.2
    - nibabel==5.1.0
    - wandb==0.15.4
    - lightning-utilities==0.9.0
    - umap-learn==0.5.4
    - SimpleITK==2.3.1